---
- hosts: haproxy
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - haproxy

- hosts: keepalived
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - keepalived
