---

- name: Copying the script for automatic configuration of the vIP interface
  copy:
    src: vmac_tweak.sh
    dest: /etc/keepalived/vmac_tweak.sh
    owner: root
    group: root
    mode: 0755

- name: Copying keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Updating net.ipv4.ip_nonlocal_bind parameter
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_nonlocal_bind=1'
  notify: Updating sysctl parameters

- name: Updating net.ipv4.ip_forward parameter
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'
  notify: Updating sysctl parameters

- name: Enable keepalived to be started at boot
  service: name=keepalived enabled=yes state=started
