---
- name: Install selinux python packages [RHEL]
  package:
    name:
      - "libselinux-python"
      - "policycoreutils-python"
      - "libsemanage-python"
    state: present

- name: Allow haproxy to listen on tcp ports {{ listen_ports }}
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: http_port_t
    state: present
  with_items:
    - "{{ listen_ports }}"

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Install haproxy
  yum: name="{{ item }}" state=present
  with_items:
    - epel-release
    - haproxy

- name: Deploy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Enable haproxy to be started at boot
  service: name=haproxy enabled=yes state=started
